spring:
    application:
        name: server-center

server:
    port: 9000 #启动端口

eureka:
     instance:  
        hostname: localhost
        home-page-url: http://${eureka.instance.hostname}:${server.port}/ 
     client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        service-url:
          defaultZone: http://zhanghw:123456@${eureka.instance.hostname}:${server.port}/
          

# 安全认证的配置  
security:  
  basic:  
    enabled: true  
  user:  
    name: zhanghw  # 用户名  
    password: 123456   # 用户密码  